# Generated by Django 5.2.13 on 2026-04-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_days', models.IntegerField(default=0)),
                ('total_working_days', models.IntegerField(default=26)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
                ('salary_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary.salarystructure')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
